### ISSUE TITLE
RUNNING ERROR

### ISSUE THREAD

**Issue by pilubt** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#10]
=== RESTART: C:\CryptoStuffPy\python-binance\examples\Private_TriArbBot.py ===
1361
<__main__.Binance object at 0x00000267FDBE9A90>

---------------------------------------------------------

Hello and Welcome to the Binance Arbitrage Crypto Trader Bot Python Script
Created 2018 by Joaquin Roibal (@BlockchainEng)A quick 'run-through' will be performed to introduce you to the functionality of this bot
To learn more visit medium.com/@BlockchainEng or watch introductory Youtube Videos
Copyright 2018 by Joaquin Roibal

Bot Start Time: 2018-08-25 16:09:46.777794

Traceback (most recent call last):
  File "C:\CryptoStuffPy\python-binance\examples\Private_TriArbBot.py", line 555, in <module>
    run()
  File "C:\CryptoStuffPy\python-binance\examples\Private_TriArbBot.py", line 71, in run
    initialize_arb()
  File "C:\CryptoStuffPy\python-binance\examples\Private_TriArbBot.py", line 93, in initialize_arb
    pprint(balance)
TypeError: 'module' object is not callable

**Comment by Roibal** [comment]
I'm not sure, perhaps try commenting out #pprint(balance) , let me know what happens after that. Did you install Roibal/Python-Binance/ fork ?

**Comment by Roibal** [comment]
the bot seems to be running, it could be just from the pprint

**Comment by Roibal** [comment]
Please comment if any further issues arise.
