### ISSUE TITLE
AttributeError: type object 'Client' has no attribute 'synced'

### ISSUE THREAD

**Issue by izzy84** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#16]
FAILURE INITIALIZE
Traceback (most recent call last):

  File "C:\Users\izzy\Documents\arbitrage project\Private_TriArbBot.py", line 555, in <module>
    run()
  File "C:\Users\izzy\Documents\arbitrage project\Private_TriArbBot.py", line 71, in run
    initialize_arb()
  File "C:\Users\izzy\Documents\arbitrage project\Private_TriArbBot.py", line 100, in initialize_arb
    status = Client.synced('get_system_status()')
AttributeError: type object 'Client' has no attribute 'synced'

**Comment by Roibal** [comment]
Hi @izzy84 -- First off, you are using an older version of the triangular arbitrage bot, the newest one is simply called crypto_tri_arb.py (or something similar) in the main folder. Secondly, the reason for the 'synced' was due to the error "order time is 1000 ms ahead of binance time" that many of us have faced. The newest bot does not rely on synced.
