### ISSUE TITLE
'module' object is not callable  FAILURE INITIALIZE

### ISSUE THREAD

**Issue by PwnAppleTea** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#30]
Hello, I get the following when I get an attempt to placing an ARB order:

Binance Arbitrage Function Data Collection - Running

List of Arbitrage Symbols: ['ETHBTC', 'EOSETH', 'EOSBTC']
Currency Pair: ETHBTC Exchange Rate: 0.03565200 
Currency Pair: EOSETH Exchange Rate: 0.02635400 
Currency Pair: EOSBTC Exchange Rate: 0.00094040 
[0.035652, 0.026354, 0.0009404, datetime.datetime(2019, 3, 1, 10, 45, 5, 350313)]
Buy: 0.035652
Sell: 0.03568338772102907
Arbitrage Possibility - Potential Profit (Percentage): 0.0879617184176885%

Potential Fees (Percentage): 0.30000000000000004
Adjusted Profit (Percentage): -0.21203828158231153
PLACING ORDER

STARTING TRI ARB PAPER TRADING FUNCTION

'module' object is not callable

FAILURE INITIALIZE

Restarting

**Comment by PwnAppleTea** [comment]
I also made an adjustment here:

def arbitrage_bin(list_of_sym, tickers, portfolio, cycle_num=1, cycle_time=30, **place_order='Yes', real_order='Yes'**):

**Comment by Roibal** [comment]
Hi, are you using Tri Arb Trader? I have been seening this exact error 'module not callable' many times from different sources, this seems to be the new bottleneck / source of errors. Can you find out which lines are running and which line causes that error?

**Comment by PwnAppleTea** [comment]
> 
> 
> Hi, are you using Tri Arb Trader? I have been seening this exact error 'module not callable' many times from different sources, this seems to be the new bottleneck / source of errors. Can you find out which lines are running and which line causes that error?

Hello, yes this is from BinanceTriArbTrader.py

**Comment by PwnAppleTea** [comment]
I believe that I have found these lines to have been the issue:

PLACING ORDER

STARTING TRI ARB PAPER TRADING FUNCTION

Traceback (most recent call last):
  File "E:/RoibalCrypto/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/Private_TriArbBot.py", line 990, in <module>
    run()
  File "E:/RoibalCrypto/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/Private_TriArbBot.py", line 69, in run
    initialize_arb()
  File "E:/RoibalCrypto/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/Private_TriArbBot.py", line 452, in initialize_arb
    calc_profit_list.append(arbitrage_bin(arb_market, tickers, portfolio, 1, 1))
  File "E:/RoibalCrypto/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/Private_TriArbBot.py", line 643, in arbitrage_bin
    portfolio, start, coin2, coin3, final = tri_arb_paper(portfolio, list_of_sym, exch_rate_list)
  File "E:/RoibalCrypto/python-binance-master/examples/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/Private_TriArbBot.py", line 820, in tri_arb_paper
    pprint(tri_arb_paper_msg)
TypeError: 'module' object is not callable

FAILURE INITIALIZE
