### ISSUE TITLE
initialize issue - import save_historical_data_Roibal

### ISSUE THREAD

**Issue by Genson-G** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#31]
Struggling to initialize getting the following error: Traceback (most recent call last):
  File "/Users/genson/PycharmProjects/python-binance-master/examples/Crypto-Trading-Bots/Roibal_BinanceBot.py", line 29, in <module>
    import save_historical_data_Roibal
ImportError: No module named save_historical_data_Roibal

**Comment by izced** [comment]
Nearly same Error on Ubuntu

Hello and Welcome to the Crypto Trader Bot Python Script
Created 2018 by Joaquin Roibal (@BlockchainEng)
A quick 'run-through' will be performed to introduce you to the functionality of this bot
To learn more visit medium.com/@BlockchainEng or watch introductory Youtube Videos
Traceback (most recent call last):
  File "Roibal_BinanceBot.py", line 347, in <module>
    run()
  File "Roibal_BinanceBot.py", line 54, in run
    save_historical_data_Roibal.save_historic_klines_csv('BTCUSDT', "1 hours ago UTC", "now UTC", Client.KLINE_INTERVAL_1MINUTE)
  File "/home/izced/Downloads/Cryptocurrency-Trading-Bots-Python-Beginner-Advance-master/save_historical_data_Roibal.py", line 284, in save_historic_klines_csv
    fig, ax = plt.subplots()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 1184, in subplots
    fig = figure(**fig_kw)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/_backend_tk.py", line 1046, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1822, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by amitkalo** [comment]
> ImportError: No module named save_historical_data_Roibal
i have the same issue but with more imports, did you solve it?
